/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nutriTelas;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import nutriClasses.ListaConsultas;
import nutriClasses.consultas;

/**
 *
 * @author rebec
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        BoasVindas = new javax.swing.JLabel();
        ExcluirConsulta = new javax.swing.JButton();
        NovaConsulta = new javax.swing.JButton();
        FinalizarConsulta = new javax.swing.JButton();
        Tabela = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sair = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(30, 30, 30));

        BoasVindas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BoasVindas.setForeground(new java.awt.Color(0, 51, 51));
        BoasVindas.setText("Boas Vindas ao sistema de agendamento!");

        ExcluirConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ExcluirConsulta.setForeground(new java.awt.Color(0, 51, 51));
        ExcluirConsulta.setText("Excluir consulta");

        NovaConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NovaConsulta.setForeground(new java.awt.Color(0, 51, 51));
        NovaConsulta.setText("Nova Consulta");
        NovaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaConsultaActionPerformed(evt);
            }
        });

        FinalizarConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FinalizarConsulta.setForeground(new java.awt.Color(0, 51, 51));
        FinalizarConsulta.setText("Finalizar Consulta");
        FinalizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarConsultaActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(102, 255, 153));
        //definindo o nome das colunas
        String[] colunas = {"Paciente:","CPF","Telefone","Data da consulta"};
        DefaultTableModel tabelaModelo = new DefaultTableModel(colunas,0);

        //pegando os dados da lista de consultas
        List<consultas> listaCompleta =ListaConsultas.Listar();

        //para item que houver na lista de consultas, adiciona uma nova linha na nossa tabela
        for(int i=0; i<listaCompleta.size(); i++){
            //extraindo os dados:
            consultas consultaAtual = listaCompleta.get(i);
            //montando a linha:
            String[] linha ={
                consultaAtual.getNome(),
                consultaAtual.getCpf(),
                consultaAtual.getTelefone(),
                consultaAtual.getData()
            };
            tabelaModelo.addRow(linha);
        }
        jTable1.setModel(tabelaModelo);
        Tabela.setViewportView(jTable1);

        sair.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        sair.setForeground(new java.awt.Color(255, 51, 51));
        sair.setText("EXIT");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoasVindas)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(NovaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ExcluirConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(FinalizarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sair))
                        .addComponent(Tabela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(BoasVindas)
                .addGap(33, 33, 33)
                .addComponent(Tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NovaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExcluirConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FinalizarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addComponent(sair, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NovaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaConsultaActionPerformed
        CadastroConsulta cadastro = new CadastroConsulta();
        cadastro.setVisible(true);
    }//GEN-LAST:event_NovaConsultaActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void FinalizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarConsultaActionPerformed
        DetalheFinalizacao finalizacao = new DetalheFinalizacao();
        finalizacao.setVisible(true);
    }//GEN-LAST:event_FinalizarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BoasVindas;
    private javax.swing.JButton ExcluirConsulta;
    private javax.swing.JButton FinalizarConsulta;
    private javax.swing.JButton NovaConsulta;
    private javax.swing.JScrollPane Tabela;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
    
}
