/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NutricionistaApp;

import javax.swing.JOptionPane;

/**
 *
 * @author rebec
 */
public class gastosCaloricos extends javax.swing.JFrame {

    /**
     * Creates new form gastosCaloricos
     */
    public gastosCaloricos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        textoTopo = new javax.swing.JLabel();
        Mulher = new javax.swing.JRadioButton();
        Homem = new javax.swing.JRadioButton();
        nivelAtividade = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        idade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        gastoBasal = new javax.swing.JLabel();
        GastoTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        buttonGroup1.add(Homem);
        buttonGroup1.add(Mulher);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gastos caloricos");

        textoTopo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        textoTopo.setForeground(new java.awt.Color(0, 51, 51));
        textoTopo.setText("Calculo de gasto calorico");

        Mulher.setText("Mulher");
        Mulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MulherActionPerformed(evt);
            }
        });

        Homem.setText("Homem");
        Homem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomemActionPerformed(evt);
            }
        });

        nivelAtividade.setBackground(new java.awt.Color(0, 204, 204));
        nivelAtividade.setEditable(true);
        nivelAtividade.setForeground(new java.awt.Color(255, 255, 255));
        nivelAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nenhuma", "leve(exercicios de 1 a 3 vezes/semana)", "Moderado (exercício moderado 3 a 5 dias/semana)", "Ativo (exercício pesado 5 a 6 dias/semana)", "Extremamente ativo (exercício pesado diário)" }));
        nivelAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelAtividadeActionPerformed(evt);
            }
        });

        jLabel2.setText("idade:");

        altura.setBackground(new java.awt.Color(0, 102, 102));
        altura.setForeground(new java.awt.Color(255, 255, 255));
        altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaActionPerformed(evt);
            }
        });

        jLabel3.setText("Peso:");

        idade.setBackground(new java.awt.Color(0, 102, 102));
        idade.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Altura:");

        peso.setBackground(new java.awt.Color(0, 102, 102));
        peso.setForeground(new java.awt.Color(255, 255, 255));
        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });

        jLabel5.setText("Nivel de atividade fisica:");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textoTopo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idade, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(peso)
                                    .addComponent(altura, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addComponent(Mulher, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Homem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nivelAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(calcular)
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(textoTopo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mulher)
                    .addComponent(Homem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nivelAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcular)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jLabel1.setText("Gasto basal:");

        jLabel6.setText("Gasto total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gastoBasal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GastoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(gastoBasal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(GastoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(voltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaActionPerformed

    private void MulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MulherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MulherActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void nivelAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelAtividadeActionPerformed

    }//GEN-LAST:event_nivelAtividadeActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
//        String strIdade = idade.getText();
//        String strAltura = altura.getText();
//        String strPeso = peso.getText();
//        
//        if(strIdade.isEmpty()||strAltura.isEmpty()||strPeso.isEmpty()){
//            JOptionPane.showMessageDialog(null, "Todos os componetes precisam ser preenchidos: ");
//        }
//        else if(!strIdade.matches("\\d+")||!strPeso.matches("\\d+")||!strAltura.matches("\\d+")){
//             JOptionPane.showMessageDialog(null, "Entrada Invalida. Digite valores numericos.");
//        }
//        else if(Integer.parseInt(idade.getText())<=0||Integer.parseInt(altura.getText())<=0||Integer.parseInt(peso.getText())<=0){
//            JOptionPane.showMessageDialog(null, "Os valores precisam ser maiores que 0: ");
//        }
//        else{
//            calculo();
//        }
        String strIdade = idade.getText();
        String strAltura = altura.getText();
        String strPeso = peso.getText();

        if (strIdade.isEmpty() || strAltura.isEmpty() || strPeso.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os componentes precisam ser preenchidos.");
        } else {
            try {
                // Tenta converter as strings para números
                int idadeValor = Integer.parseInt(strIdade);
                double alturaValor = Double.parseDouble(strAltura);
                double pesoValor = Double.parseDouble(strPeso);

                // Verifica se os valores são válidos
                if (idadeValor <= 0 || alturaValor <= 0 || pesoValor <= 0) {
                    JOptionPane.showMessageDialog(null, "Os valores precisam ser maiores que 0.");
                } else {
                    // Se todos os critérios forem atendidos, chama o método de cálculo
                    calculo();
                }
            } catch (NumberFormatException e) {
                // Captura a exceção se a conversão falhar (entrada não numérica)
                JOptionPane.showMessageDialog(null, "Entrada inválida. Digite valores numéricos válidos.");
            }
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void HomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gastosCaloricos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gastosCaloricos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gastosCaloricos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gastosCaloricos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gastosCaloricos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GastoTotal;
    private javax.swing.JRadioButton Homem;
    private javax.swing.JRadioButton Mulher;
    private javax.swing.JTextField altura;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel gastoBasal;
    private javax.swing.JTextField idade;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> nivelAtividade;
    private javax.swing.JTextField peso;
    private javax.swing.JLabel textoTopo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

    public void calculo() {
        double calbasal;
        double calTotal;
        double Ridade;
        double Raltura;
        double Rpeso;
        Ridade = Double.parseDouble(idade.getText());
        Raltura = Double.parseDouble(altura.getText());
        Rpeso = Double.parseDouble(peso.getText());

        /*if(Mulher.isSelected()){
            calbasal = 655 + (9.6*Rpeso) + (1.9 * Raltura) - (4.7 * Ridade);
            //CalBasal = 655 + (9,6 * Peso) + (1,9 * Altura) – (4,7 * Idade)
            
            //calculo total:
            if(nivelAtividade.get){
                //gasto total
            }
       
            gastoBasal.setText(""+calbasal);
            GastoTotal.setText(""+calTotal);
        }
        if(Homem.isSelected()){
             calbasal = 66 + (13.7 * Rpeso) + (5 * Raltura) - (6.8 * Ridade);
             gastoBasal.setText(""+calbasal);
        }*/
        // Calcular o valor do calbasal com base no sexo selecionado
        if (Mulher.isSelected()) {
            calbasal = 655 + (9.6 * Rpeso) + (1.9 * Raltura) - (4.7 * Ridade);
        } else if (Homem.isSelected()) {
            calbasal = 66 + (13.7 * Rpeso) + (5 * Raltura) - (6.8 * Ridade);
        } else {
            calbasal = 0;
            JOptionPane.showMessageDialog(null, "voce deve selecionar um genero sexual");
            return;
        }

        // Capturar o nível de atividade selecionado no JComboBox
        String nivel = (String) nivelAtividade.getSelectedItem();
        /* 
        nenhuma
        leve(exercicios de 1 a 3 vezes/semana)
        Moderado (exercício moderado 3 a 5 dias/semana)
        Ativo (exercício pesado 5 a 6 dias/semana)
        Extremamente ativo (exercício pesado diário)
         */
        // Calcular calTotal com base no nível de atividade selecionado
        if ("nenhuma".equals(nivel)) {
            calTotal = calbasal * 1.2;
        } else if ("leve(exercicios de 1 a 3 vezes/semana)".equals(nivel)) {
            calTotal = calbasal * 1.375;
        } else if ("Moderado (exercício moderado 3 a 5 dias/semana)".equals(nivel)) {
            calTotal = calbasal * 1.55;
        } else if ("Ativo (exercício pesado 5 a 6 dias/semana)".equals(nivel)) {
            calTotal = calbasal * 1.725;
        } else if ("Extremamente ativo (exercício pesado diário)".equals(nivel)) {
            calTotal = calbasal * 1.9;
        } else {
            calTotal = 0;
            return;
        }

        // Atualizar os textos dos JLabels gastoBasal e GastoTotal
        gastoBasal.setText("" + calbasal);
        GastoTotal.setText("" + calTotal);
    }
}
