/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NutricionistaApp;

/**
 *
 * @author rebec
 */
import javax.swing.JOptionPane;

public class imc extends javax.swing.JFrame {

    /**
     * Creates new form imc
     */
    public imc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        TituloImc = new javax.swing.JLabel();
        PesoPaciente = new javax.swing.JLabel();
        AlturaPaciente = new javax.swing.JLabel();
        ResPeso = new javax.swing.JTextField();
        ResAltura = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();
        calcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ResultadoImc = new javax.swing.JLabel();
        InterpretacaoImc = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("imc");

        TituloImc.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        TituloImc.setForeground(new java.awt.Color(0, 0, 102));
        TituloImc.setText("calcule seu imc:");

        PesoPaciente.setText("Peso: (em kg)");

        AlturaPaciente.setText("Altura: (em cm)");

        ResPeso.setBackground(new java.awt.Color(0, 51, 51));
        ResPeso.setForeground(new java.awt.Color(255, 255, 255));
        ResPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResPesoActionPerformed(evt);
            }
        });

        ResAltura.setBackground(new java.awt.Color(0, 51, 51));
        ResAltura.setForeground(new java.awt.Color(255, 255, 255));
        ResAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResAlturaActionPerformed(evt);
            }
        });

        voltar.setText("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(PesoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AlturaPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(calcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(voltar))
                            .addComponent(ResAltura))))
                .addGap(337, 337, 337))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TituloImc)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloImc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesoPaciente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlturaPaciente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular)
                    .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        ResultadoImc.setBackground(new java.awt.Color(0, 0, 0));
        ResultadoImc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        InterpretacaoImc.setBackground(new java.awt.Color(0, 0, 0));
        InterpretacaoImc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InterpretacaoImc, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResultadoImc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(ResultadoImc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InterpretacaoImc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ResPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResPesoActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed

        String strAltura = ResAltura.getText();
        String strPeso = ResPeso.getText();
        /*
        if(strAltura.isEmpty()||strPeso.isEmpty()){
             JOptionPane.showMessageDialog(null,"Todos os campos precisam ser preenchidos: ");
        }
        else if(!strAltura.matches("\\d+")||!strPeso.matches("\\d+")){
            JOptionPane.showMessageDialog(null, "Entrada Invalida. Digite valores numericos.");
        }
        else if(Integer.parseInt(ResPeso.getText())<=0||Integer.parseInt(ResAltura.getText())<=0){
            JOptionPane.showMessageDialog(null,"Os valores precisam ser maiores que 0: ");
        }
        else{
            calc();
        }*/
        if (strAltura.isEmpty() || strPeso.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos precisam ser preenchidos.");
        } else {
            try {
                // Tenta converter as strings para números
                double alturaValor = Double.parseDouble(strAltura);
                double pesoValor = Double.parseDouble(strPeso);

                // Verifica se os valores são válidos
                if (alturaValor <= 0 || pesoValor <= 0) {
                    JOptionPane.showMessageDialog(null, "Os valores precisam ser maiores que 0.");
                } else {
                    // Se todos os critérios forem atendidos, chama o método calc()
                    calc();
                }
            } catch (NumberFormatException e) {
                // Captura a exceção se a conversão falhar (entrada não numérica)
                JOptionPane.showMessageDialog(null, "Entrada inválida. Digite valores numéricos válidos.");
            }
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void ResAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResAlturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new imc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlturaPaciente;
    private javax.swing.JLabel InterpretacaoImc;
    private javax.swing.JLabel PesoPaciente;
    private javax.swing.JTextField ResAltura;
    private javax.swing.JTextField ResPeso;
    private javax.swing.JLabel ResultadoImc;
    private javax.swing.JLabel TituloImc;
    private javax.swing.JButton calcular;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
     public void calc() {
        //variaveis
        double altura;
        double peso;
        double imc;
        String mensagem;
        String imcResposta;
        String nomeApresentar;
        //capturando o que o usuario digitou
        altura = Double.parseDouble(ResAltura.getText());
        peso = Double.parseDouble(ResPeso.getText());

        //calculo
        imc = peso / (altura / 100 * altura / 100);

        //imc
        if (imc < 18.5) {
            imcResposta = "" + imc;
            mensagem = "\nMagreza, se o IMC for menor que 18,5";
        } else if (imc < 24.9) {
            imcResposta = "" + imc;
            mensagem = "\nNormal, se o IMC for entre 18,5 e 24,9";
        } else if (imc < 29.9) {
            imcResposta = "" + imc;
            mensagem = "\nSobrepeso, se o IMC for entre 25 e 29,9";
        } else if (imc < 30) {
            imcResposta = "" + imc;
            mensagem = "\nObesidade, se o IMC for entre 30 e 39,9";
        } else {
            imcResposta = "" + imc;
            mensagem = "\nObesidade grave, se o IMC for maior ou igual a 40";
        }
        ResultadoImc.setText(imcResposta);
        InterpretacaoImc.setText(mensagem);
    }

}
